# Generated by Django 5.0.2 on 2024-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ragister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobilenumber', models.IntegerField()),
                ('Dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('company_n', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
            ],
        ),
    ]
